# Generated by Django 5.1.5 on 2025-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(related_name='trips', to='destinations.destination'),
        ),
    ]
