# Generated by Django 5.1.5 on 2025-03-04 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('trips', '0002_alter_trip_destinations'),
        ('users', '0003_remove_profile_address_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.TextField(blank=True, help_text='List of planned activities (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload trip cover image', null=True, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.profile'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='trips_trip_start_d_290e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
    ]
